/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.samho.apresentacao;

import com.samho.negocio.Aparencias;
import com.samho.util.Util;
import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 * Classe para visualização de objetos do tipo FrmManutencao.
 *
 * @author Saibel, Sergio Luis
 * @since  date 25/03/2014
 *
 * @version  revision 001.20140325 date 25/03/2014 author Saibel, Sérgio Luis reason
 * Conseguir instanciar um objeto do tipo FrmMaunutenção com os atributos e
 * métodos necessários. Esta classe servirá como base para todos os FRMs de
 * manutenção.
 */
public class IFrmManAparencia extends JInternalFrame {

    // Declaração de atributos
    private final Aparencias aparencia;
    private final JLabel lblImagemFundo;
    private final JFrame jFrame;
    private String imagemFundoOLD;
    private UIManager.LookAndFeelInfo[] looks = UIManager.getInstalledLookAndFeels();
    

    // Construtor
    public IFrmManAparencia(JLabel lblImagemFundo, JFrame jFrame) {
        initComponents();

        Util.limparCampos(rootPane);

        this.lblImagemFundo = lblImagemFundo;
        this.jFrame = jFrame;

        aparencia = new Aparencias();

        carregarObjetoIFrmManutencao();
    }

    public final void carregarObjetoIFrmManutencao() {
        try {
            aparencia.carregarPropriedades();
            imagemFundoOLD = aparencia.getCaminhoImagemFundo();
            txtCaminhoImagemFundo.setText(aparencia.getCaminhoImagemFundo());
            
            cbLookAndFeel.removeAllItems();
            for (UIManager.LookAndFeelInfo look : looks) {
                cbLookAndFeel.addItem(look.getName());
            } 
            cbLookAndFeel.setSelectedItem(aparencia.getLookAndFeel());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this.getParent(),
                    "Arquivo nao pode ser carregado.\n\nMotivo: " + ex);
        }
    }

    private void reescreverObjeto() {
        try {
            aparencia.setCaminhoImagemFundo(txtCaminhoImagemFundo.getText());
            aparencia.setLookAndFeel(cbLookAndFeel.getSelectedItem().toString());

            aparencia.descarregarPropriedades();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this.getParent(),
                    "Arquivo nao pode ser reescrito.\n\nMotivo: " + ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcSelecionarArquivo = new javax.swing.JFileChooser();
        tablManutencao = new javax.swing.JTabbedPane();
        pnlGeral = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtCaminhoImagemFundo = new javax.swing.JTextField();
        lblSelCaminhoImagemFundo = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbLookAndFeel = new javax.swing.JComboBox();
        pnlBotoes = new javax.swing.JPanel();
        btnAplicar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        btnAjudar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        mnuBarPrincipal = new javax.swing.JMenuBar();
        mnuArquivos = new javax.swing.JMenu();
        mnuAjuda = new javax.swing.JMenu();

        fcSelecionarArquivo.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurações de Aparência do SAMHO");
        setMaximumSize(new java.awt.Dimension(730, 210));
        setMinimumSize(new java.awt.Dimension(730, 210));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(730, 210));
        setVerifyInputWhenFocusTarget(false);
        getContentPane().setLayout(null);

        tablManutencao.setMinimumSize(new java.awt.Dimension(713, 245));
        tablManutencao.setName(""); // NOI18N

        pnlGeral.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Caminho: Imagem de Fundo");
        pnlGeral.add(jLabel11);
        jLabel11.setBounds(40, 50, 157, 14);

        txtCaminhoImagemFundo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCaminhoImagemFundo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtCaminhoImagemFundoPropertyChange(evt);
            }
        });
        pnlGeral.add(txtCaminhoImagemFundo);
        txtCaminhoImagemFundo.setBounds(200, 11, 472, 20);

        lblSelCaminhoImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/pesquisar.png"))); // NOI18N
        lblSelCaminhoImagemFundo.setToolTipText("Selecionar arquivo: pg_restore.exe");
        lblSelCaminhoImagemFundo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSelCaminhoImagemFundo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblSelCaminhoImagemFundoMouseReleased(evt);
            }
        });
        pnlGeral.add(lblSelCaminhoImagemFundo);
        lblSelCaminhoImagemFundo.setBounds(676, 11, 20, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Caminho: Imagem de Fundo");
        pnlGeral.add(jLabel12);
        jLabel12.setBounds(39, 14, 157, 14);

        cbLookAndFeel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlGeral.add(cbLookAndFeel);
        cbLookAndFeel.setBounds(200, 48, 169, 20);

        tablManutencao.addTab("Geral", pnlGeral);

        getContentPane().add(tablManutencao);
        tablManutencao.setBounds(0, 0, 713, 113);
        tablManutencao.getAccessibleContext().setAccessibleName("");

        pnlBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        pnlBotoes.setName("pnlBotao"); // NOI18N
        pnlBotoes.setPreferredSize(new java.awt.Dimension(229, 33));

        btnAplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/aplicar.png"))); // NOI18N
        btnAplicar.setText("Aplicar");
        btnAplicar.setToolTipText("");
        btnAplicar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAplicar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnAplicar.setMaximumSize(new java.awt.Dimension(70, 20));
        btnAplicar.setMinimumSize(new java.awt.Dimension(70, 20));
        btnAplicar.setName("btnCancelar"); // NOI18N
        btnAplicar.setPreferredSize(new java.awt.Dimension(85, 25));
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/confirmar.png"))); // NOI18N
        btnConfirmar.setText("Ok");
        btnConfirmar.setToolTipText("");
        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnConfirmar.setMaximumSize(new java.awt.Dimension(70, 20));
        btnConfirmar.setMinimumSize(new java.awt.Dimension(70, 20));
        btnConfirmar.setName("btnConfirmar"); // NOI18N
        btnConfirmar.setPreferredSize(new java.awt.Dimension(85, 25));
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnAjudar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ajudar.png"))); // NOI18N
        btnAjudar.setToolTipText("");
        btnAjudar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjudar.setMargin(new java.awt.Insets(5, 5, 5, 5));
        btnAjudar.setMaximumSize(new java.awt.Dimension(70, 20));
        btnAjudar.setMinimumSize(new java.awt.Dimension(70, 20));
        btnAjudar.setName("btnAjudar"); // NOI18N
        btnAjudar.setPreferredSize(new java.awt.Dimension(85, 25));
        btnAjudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjudarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnCancelar.setMaximumSize(new java.awt.Dimension(70, 20));
        btnCancelar.setMinimumSize(new java.awt.Dimension(70, 20));
        btnCancelar.setName("btnCancelar"); // NOI18N
        btnCancelar.setPreferredSize(new java.awt.Dimension(85, 25));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotoesLayout = new javax.swing.GroupLayout(pnlBotoes);
        pnlBotoes.setLayout(pnlBotoesLayout);
        pnlBotoesLayout.setHorizontalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAjudar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 409, Short.MAX_VALUE)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBotoesLayout.setVerticalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjudar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBotoes);
        pnlBotoes.setBounds(0, 119, 713, 38);

        mnuArquivos.setText("Arquivo");
        mnuBarPrincipal.add(mnuArquivos);

        mnuAjuda.setText("Ajuda");
        mnuBarPrincipal.add(mnuAjuda);

        setJMenuBar(mnuBarPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
            reescreverObjeto();

            JOptionPane.showMessageDialog(this.getParent(),
                    "Arquivo salvo com sucesso.");

            aparencia.aplicarAparenciaImagemFundoJLabel(lblImagemFundo);
            aparencia.aplicarAparenciaLookAndFeel(jFrame);

            this.dispose();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this.getParent(),
                    "Arquivo não pode ser salvo.\n\nMotivo: " + e);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        aparencia.setCaminhoImagemFundo(imagemFundoOLD);
        aparencia.aplicarAparenciaImagemFundoJLabel(lblImagemFundo);

        Util.cancelar(this);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAjudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjudarActionPerformed
        Util.ajudar("IFrmManAparencia");
    }//GEN-LAST:event_btnAjudarActionPerformed

    private void lblSelCaminhoImagemFundoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSelCaminhoImagemFundoMouseReleased
        try {
            fcSelecionarArquivo.setSelectedFile(
                    new File(txtCaminhoImagemFundo.getText()));
            int returnVal = fcSelecionarArquivo.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                txtCaminhoImagemFundo.setText(
                        fcSelecionarArquivo.getSelectedFile().getAbsolutePath());
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this.getParent(),
                    "Caminho não pode ser localizado.\n\nMotivo: " + e);
        }
    }//GEN-LAST:event_lblSelCaminhoImagemFundoMouseReleased

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
        aparencia.setCaminhoImagemFundo(txtCaminhoImagemFundo.getText());
        aparencia.setLookAndFeel(cbLookAndFeel.getSelectedItem().toString());
        
        aparencia.aplicarAparenciaImagemFundoJLabel(lblImagemFundo);
        aparencia.aplicarAparenciaLookAndFeel(jFrame);
    }//GEN-LAST:event_btnAplicarActionPerformed

    private void txtCaminhoImagemFundoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtCaminhoImagemFundoPropertyChange
        if (evt.getPropertyName().equals("text")) {
            btnAplicar.setEnabled(!txtCaminhoImagemFundo.getText().equals(""));
        }
    }//GEN-LAST:event_txtCaminhoImagemFundoPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjudar;
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox cbLookAndFeel;
    private javax.swing.JFileChooser fcSelecionarArquivo;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel lblSelCaminhoImagemFundo;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuArquivos;
    private javax.swing.JMenuBar mnuBarPrincipal;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JPanel pnlGeral;
    private javax.swing.JTabbedPane tablManutencao;
    private javax.swing.JTextField txtCaminhoImagemFundo;
    // End of variables declaration//GEN-END:variables
}
