/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.samho.apresentacao;

import com.samho.negocio.Principal;
import com.samho.negocio.Telefones;
import com.samho.negocio.TiposTelefones;
import com.samho.util.Formatacao;
import com.samho.util.JTextFieldDocument;
import com.samho.util.Util;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 * Classe para visualização de objetos do tipo FrmManutencao.
 *
 * @author Saibel, Sergio Luis
 * @since  date 31/03/2017
 *
 * @version  revision 001.20170331 date 31/03/2017 author Saibel, Sérgio Luis reason
 * Conseguir instanciar um objeto do tipo FrmMaunutenção com os atributos e
 * métodos necessários. Esta classe tem como objetivo manipular os objetos 
 * definidos e ou obtidos a fim de manipular informações.
 * Esta extende um JInternalFrame ou seja necessita de um Frame como pai.
 * Métodos principais: Definição, Obtenção e Visualização do objeto.
 * Métodos secundários: Pesquisa de tipos de telefones
 * 
 */
public final class IFrmManTelefone extends JInternalFrame {

    // Declaração de atributos
    private Telefones telefone;

    // Construtor
    public IFrmManTelefone(Telefones telefone) throws Exception {
        initComponents();
        
        Formatacao.reformatarTelefone(txtNumero);
        
        Util.limparCampos(rootPane);

        this.telefone = telefone;

        // Permite que somente números sejam informados neste campo
        txtCodigo.setDocument(new JTextFieldDocument(true));
        txtCodTipoTelefone.setDocument(new JTextFieldDocument(true));
        //txtNumero.setDocument(new JTextFieldDocument(true));
        txtRamal.setDocument(new JTextFieldDocument(true));
        // Converte para caixa alta a string informada no campo
        txtContato.setDocument(new JTextFieldDocument(false));

        carregarObjetoIFrmManutencao(telefone);
    }

    public void carregarObjetoIFrmManutencao(Telefones telefone) {
        try {
            if (telefone.getIdTelefone() != -1) {
                txtCodigo.setText(String.valueOf(telefone.getIdTelefone()));
            } else {
                txtCodigo.setText(String.valueOf(
                        telefone.getTelefonesDAO().getProximoID()));
            }

            txtCodTipoTelefone.setText(String.valueOf(telefone.getCodTipoTelefone()));
            pesquisarCodigoDescicaoTipoTelefone(new TiposTelefones());

            txtNumero.setText(String.valueOf(telefone.getNumero()));
            txtRamal.setText(String.valueOf(telefone.getRamal()));
            txtContato.setText(telefone.getContato());
            chkAtivo.setSelected(telefone.isAtivo());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this.getParent(),
                    "Registro nao pode ser carregado.\n\nMotivo: " + ex);
        }
    }

    private void reescreverObjeto() {
        try {
            telefone.setIdTelefone(Long.parseUnsignedLong(txtCodigo.getText()));
            telefone.setCodTipoTelefone(Long.parseUnsignedLong(
                    txtCodTipoTelefone.getText()));
            telefone.setNumero(Long.parseUnsignedLong(
                    Formatacao.removerFormatacao(txtNumero.getText())));
            telefone.setRamal(Long.parseUnsignedLong(txtRamal.getText()));
            telefone.setContato(txtContato.getText());
            telefone.setAtivo(chkAtivo.isSelected());

            telefone.adicionarCampos();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this.getParent(),
                    "Registro nao pode ser reescrito.\n\nMotivo: " + ex);
        }
    }

    public void pesquisarCodigoDescicaoTipoTelefone(TiposTelefones tipoTelefone) {
        Util.pesquisarCodigoDescicao(
                tipoTelefone, txtCodTipoTelefone, txtDescrTipoTelefone);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablManutencao = new javax.swing.JTabbedPane();
        pnlGeral = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodTipoTelefone = new javax.swing.JTextField();
        lblLocalizarTipoTelefone = new javax.swing.JLabel();
        txtDescrTipoTelefone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRamal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtContato = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        chkAtivo = new javax.swing.JCheckBox();
        pnlBotoes = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        btnAjudar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        mnuBarPrincipal = new javax.swing.JMenuBar();
        mnuArquivos = new javax.swing.JMenu();
        mnuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Telefone");
        setMaximumSize(new java.awt.Dimension(730, 244));
        setMinimumSize(new java.awt.Dimension(730, 244));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(730, 244));
        setVerifyInputWhenFocusTarget(false);
        getContentPane().setLayout(null);

        tablManutencao.setMinimumSize(new java.awt.Dimension(713, 245));
        tablManutencao.setName(""); // NOI18N

        pnlGeral.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Cód. Telefone");
        pnlGeral.add(jLabel2);
        jLabel2.setBounds(79, 14, 76, 14);

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(java.awt.SystemColor.info);
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pnlGeral.add(txtCodigo);
        txtCodigo.setBounds(159, 11, 69, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Cód. Tipo Tel.");
        pnlGeral.add(jLabel3);
        jLabel3.setBounds(81, 40, 74, 14);

        txtCodTipoTelefone.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCodTipoTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodTipoTelefoneFocusLost(evt);
            }
        });
        pnlGeral.add(txtCodTipoTelefone);
        txtCodTipoTelefone.setBounds(159, 37, 70, 20);

        lblLocalizarTipoTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/localizar.png"))); // NOI18N
        lblLocalizarTipoTelefone.setToolTipText("Localizar um tipo de telefone já cadastrado.");
        lblLocalizarTipoTelefone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLocalizarTipoTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblLocalizarTipoTelefoneMouseReleased(evt);
            }
        });
        pnlGeral.add(lblLocalizarTipoTelefone);
        lblLocalizarTipoTelefone.setBounds(233, 37, 20, 20);

        txtDescrTipoTelefone.setEditable(false);
        txtDescrTipoTelefone.setBackground(java.awt.SystemColor.info);
        txtDescrTipoTelefone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pnlGeral.add(txtDescrTipoTelefone);
        txtDescrTipoTelefone.setBounds(257, 37, 402, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Número");
        pnlGeral.add(jLabel8);
        jLabel8.setBounds(111, 66, 44, 14);

        try {
            txtNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNumero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumeroFocusGained(evt);
            }
        });
        pnlGeral.add(txtNumero);
        txtNumero.setBounds(159, 63, 100, 20);

        jLabel4.setText("Ramal");
        pnlGeral.add(jLabel4);
        jLabel4.setBounds(285, 66, 29, 14);

        txtRamal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRamal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRamalFocusGained(evt);
            }
        });
        pnlGeral.add(txtRamal);
        txtRamal.setBounds(318, 63, 70, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Contato");
        pnlGeral.add(jLabel6);
        jLabel6.setBounds(410, 66, 45, 14);

        txtContato.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pnlGeral.add(txtContato);
        txtContato.setBounds(459, 63, 200, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Ativo");
        pnlGeral.add(jLabel7);
        jLabel7.setBounds(125, 89, 30, 14);

        chkAtivo.setToolTipText("");
        pnlGeral.add(chkAtivo);
        chkAtivo.setBounds(159, 86, 21, 21);

        tablManutencao.addTab("Geral", pnlGeral);

        getContentPane().add(tablManutencao);
        tablManutencao.setBounds(0, 0, 710, 148);
        tablManutencao.getAccessibleContext().setAccessibleName("");

        pnlBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        pnlBotoes.setName("pnlBotao"); // NOI18N
        pnlBotoes.setPreferredSize(new java.awt.Dimension(229, 33));

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/confirmar.png"))); // NOI18N
        btnConfirmar.setText("Ok");
        btnConfirmar.setToolTipText("");
        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnConfirmar.setMaximumSize(new java.awt.Dimension(70, 20));
        btnConfirmar.setMinimumSize(new java.awt.Dimension(70, 20));
        btnConfirmar.setName("btnConfirmar"); // NOI18N
        btnConfirmar.setPreferredSize(new java.awt.Dimension(85, 25));
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnAjudar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ajudar.png"))); // NOI18N
        btnAjudar.setToolTipText("");
        btnAjudar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjudar.setMargin(new java.awt.Insets(5, 5, 5, 5));
        btnAjudar.setMaximumSize(new java.awt.Dimension(70, 20));
        btnAjudar.setMinimumSize(new java.awt.Dimension(70, 20));
        btnAjudar.setName("btnAjudar"); // NOI18N
        btnAjudar.setPreferredSize(new java.awt.Dimension(85, 25));
        btnAjudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjudarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnCancelar.setMaximumSize(new java.awt.Dimension(70, 20));
        btnCancelar.setMinimumSize(new java.awt.Dimension(70, 20));
        btnCancelar.setName("btnCancelar"); // NOI18N
        btnCancelar.setPreferredSize(new java.awt.Dimension(85, 25));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotoesLayout = new javax.swing.GroupLayout(pnlBotoes);
        pnlBotoes.setLayout(pnlBotoesLayout);
        pnlBotoesLayout.setHorizontalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAjudar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        pnlBotoesLayout.setVerticalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAjudar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBotoes);
        pnlBotoes.setBounds(0, 154, 713, 38);

        mnuArquivos.setText("Arquivo");
        mnuBarPrincipal.add(mnuArquivos);

        mnuAjuda.setText("Ajuda");
        mnuBarPrincipal.add(mnuAjuda);

        setJMenuBar(mnuBarPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        reescreverObjeto();

        Util.salvar(telefone, this, true);
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Util.cancelar(this);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAjudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjudarActionPerformed
        Util.ajudar();
    }//GEN-LAST:event_btnAjudarActionPerformed

    private void lblLocalizarTipoTelefoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLocalizarTipoTelefoneMouseReleased
        boolean[] acoes = Util.getAcoesUsuario(Principal.TIPOS_TELEFONES);

        if (!acoes[Util.CONSULTAR]) {
            JOptionPane.showMessageDialog(this.getParent(),
                    "Você não pode efetuar esta consulta.\n\nMotivo: "
                            + "Usuário sem permissão.");
        } else {         
            try {
                IFrmPesqTiposTelefones iFrmPesqTiposTelefones
                        = new IFrmPesqTiposTelefones(new IFrmManTipoTelefone(
                                        new TiposTelefones()), txtCodTipoTelefone,
                                txtDescrTipoTelefone);

                this.getParent().remove(iFrmPesqTiposTelefones);
                this.getParent().add(iFrmPesqTiposTelefones);

                Util.centralizar(this.getParent(), iFrmPesqTiposTelefones);

                iFrmPesqTiposTelefones.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this.getParent(),
                        "Tipo de endereço não pode ser consultada.\n\nMotivo: " + e);
            }
        }
    }//GEN-LAST:event_lblLocalizarTipoTelefoneMouseReleased

    private void txtCodTipoTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodTipoTelefoneFocusLost
        pesquisarCodigoDescicaoTipoTelefone(new TiposTelefones());
    }//GEN-LAST:event_txtCodTipoTelefoneFocusLost

    private void txtNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroFocusGained
        txtNumero.selectAll();
    }//GEN-LAST:event_txtNumeroFocusGained

    private void txtRamalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRamalFocusGained
        txtRamal.selectAll();
    }//GEN-LAST:event_txtRamalFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjudar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JCheckBox chkAtivo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblLocalizarTipoTelefone;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuArquivos;
    private javax.swing.JMenuBar mnuBarPrincipal;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JPanel pnlGeral;
    private javax.swing.JTabbedPane tablManutencao;
    private javax.swing.JTextField txtCodTipoTelefone;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtContato;
    private javax.swing.JTextField txtDescrTipoTelefone;
    private javax.swing.JFormattedTextField txtNumero;
    private javax.swing.JTextField txtRamal;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the telefone
     */
    public Telefones getTelefone() {
        return telefone;
    }

    /**
     * @param telefone the telefone to set
     */
    public void setTelefone(Telefones telefone) {
        this.telefone = telefone;
    }

}
