/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.samho.apresentacao;

import com.samho.negocio.Bairros;
import com.samho.negocio.Enderecos;
import com.samho.negocio.Principal;
import com.samho.negocio.TiposEnderecos;
import com.samho.util.Formatacao;
import com.samho.util.JTextFieldDocument;
import com.samho.util.Util;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 * Classe para visualização de objetos do tipo FrmManutencao.
 *
 * @author Saibel, Sergio Luis
 * @since  date 31/03/2017
 *
 * @version  revision 001.20170331 date 31/03/2017 author Saibel, Sérgio Luis reason
 * Conseguir instanciar um objeto do tipo FrmMaunutenção com os atributos e
 * métodos necessários. Esta classe tem como objetivo manipular os objetos 
 * definidos e ou obtidos a fim de manipular informações.
 * Esta extende um JInternalFrame ou seja necessita de um Frame como pai.
 * Métodos principais: Definição, Obtenção e Visualização do objeto.
 * Métodos secundários: Pesquisa de tipos de endereço e bairros
 * 
 */
public final class IFrmManEndereco extends JInternalFrame {

    // Declaração de atributos
    private Enderecos endereco;

    // Construtor
    public IFrmManEndereco(Enderecos endereco) throws Exception {
        initComponents();
        
        Formatacao.reformatarCep(txtCEP);

        Util.limparCampos(rootPane);

        this.endereco = endereco;

        // Permite que somente números sejam informados neste campo
        txtCodigo.setDocument(new JTextFieldDocument(true));
        txtCodTipoEnder.setDocument(new JTextFieldDocument(true));
        txtCodBairro.setDocument(new JTextFieldDocument(true));
        //txtCEP.setDocument(new JTextFieldDocument(true));
        // Converte para caixa alta a string informada no campo
        txtDescicao.setDocument(new JTextFieldDocument(false));
        txtComplemento.setDocument(new JTextFieldDocument(false));

        carregarObjetoIFrmManutencao(endereco);
    }

    public void carregarObjetoIFrmManutencao(Enderecos endereco) {
        try {
            if (endereco.getIdEndereco() != -1) {
                txtCodigo.setText(String.valueOf(endereco.getIdEndereco()));
            } else {
                txtCodigo.setText(String.valueOf(
                        endereco.getEnderecoDAO().getProximoID()));
            }

            txtCodTipoEnder.setText(String.valueOf(endereco.getCodTipoEndereco()));
            pesquisarCodigoDescicaoTipoEndereco(new TiposEnderecos());

            txtCodBairro.setText(String.valueOf(endereco.getCodBairro()));
            pesquisarCodigoDescicaoBairro(new Bairros());

            txtDescicao.setText(endereco.getDescricao());
            txtComplemento.setText(endereco.getComplemento());
            txtCEP.setText(Formatacao.removerFormatacao(String.valueOf(
                    endereco.getCep())));
            chkAtivo.setSelected(endereco.isAtivo());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this.getParent(),
                    "Registro nao pode ser carregado.\n\nMotivo: " + ex);
        }
    }

    private void reescreverObjeto() {
        try {
            endereco.setIdEndereco(Long.parseUnsignedLong(txtCodigo.getText()));
            endereco.setCodTipoEndereco(Long.parseUnsignedLong(
                    txtCodTipoEnder.getText()));
            endereco.setCodBairro(Long.parseUnsignedLong(txtCodBairro.getText()));
            endereco.setDescricao(txtDescicao.getText());
            endereco.setCep(Long.parseUnsignedLong(Formatacao.removerFormatacao(
                    txtCEP.getText())));
            endereco.setComplemento(txtComplemento.getText());
            endereco.setAtivo(chkAtivo.isSelected());

            endereco.adicionarCampos();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this.getParent(),
                    "Registro nao pode ser reescrito.\n\nMotivo: " + ex);
        }
    }

    public void pesquisarCodigoDescicaoTipoEndereco(TiposEnderecos tipoEndereco) {
        Util.pesquisarCodigoDescicao(tipoEndereco, txtCodTipoEnder,
                txtDescrTipoEnder);
    }

    public void pesquisarCodigoDescicaoBairro(Bairros bairro) {
        Util.pesquisarCodigoDescicao(bairro, txtCodBairro, txtDescrBairro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablManutencao = new javax.swing.JTabbedPane();
        pnlGeral = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodTipoEnder = new javax.swing.JTextField();
        lblLocalizarTipoEnder = new javax.swing.JLabel();
        txtDescrTipoEnder = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodBairro = new javax.swing.JTextField();
        lblLocalizarBairro = new javax.swing.JLabel();
        txtDescrBairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDescicao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCEP = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        chkAtivo = new javax.swing.JCheckBox();
        pnlBotoes = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        btnAjudar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        mnuBarPrincipal = new javax.swing.JMenuBar();
        mnuArquivos = new javax.swing.JMenu();
        mnuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Endereço");
        setMaximumSize(new java.awt.Dimension(730, 290));
        setMinimumSize(new java.awt.Dimension(730, 290));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(730, 290));
        setVerifyInputWhenFocusTarget(false);
        getContentPane().setLayout(null);

        tablManutencao.setMinimumSize(new java.awt.Dimension(713, 245));
        tablManutencao.setName(""); // NOI18N

        pnlGeral.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Cód. Endereço");
        pnlGeral.add(jLabel2);
        jLabel2.setBounds(83, 14, 79, 14);

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(java.awt.SystemColor.info);
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pnlGeral.add(txtCodigo);
        txtCodigo.setBounds(166, 11, 70, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Cód. Tipo Ender.");
        pnlGeral.add(jLabel3);
        jLabel3.setBounds(73, 40, 89, 14);

        txtCodTipoEnder.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCodTipoEnder.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodTipoEnderFocusLost(evt);
            }
        });
        pnlGeral.add(txtCodTipoEnder);
        txtCodTipoEnder.setBounds(166, 37, 70, 20);

        lblLocalizarTipoEnder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/localizar.png"))); // NOI18N
        lblLocalizarTipoEnder.setToolTipText("Localizar um tipo de endereço já cadastrado.");
        lblLocalizarTipoEnder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLocalizarTipoEnder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblLocalizarTipoEnderMouseReleased(evt);
            }
        });
        pnlGeral.add(lblLocalizarTipoEnder);
        lblLocalizarTipoEnder.setBounds(240, 37, 20, 20);

        txtDescrTipoEnder.setEditable(false);
        txtDescrTipoEnder.setBackground(java.awt.SystemColor.info);
        txtDescrTipoEnder.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pnlGeral.add(txtDescrTipoEnder);
        txtDescrTipoEnder.setBounds(264, 37, 402, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Cód. Bairro");
        pnlGeral.add(jLabel4);
        jLabel4.setBounds(101, 66, 61, 14);

        txtCodBairro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCodBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodBairroFocusLost(evt);
            }
        });
        pnlGeral.add(txtCodBairro);
        txtCodBairro.setBounds(166, 63, 70, 20);

        lblLocalizarBairro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/localizar.png"))); // NOI18N
        lblLocalizarBairro.setToolTipText("Localizar um bairro já cadastrado.");
        lblLocalizarBairro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLocalizarBairro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblLocalizarBairroMouseReleased(evt);
            }
        });
        pnlGeral.add(lblLocalizarBairro);
        lblLocalizarBairro.setBounds(240, 63, 20, 20);

        txtDescrBairro.setEditable(false);
        txtDescrBairro.setBackground(java.awt.SystemColor.info);
        txtDescrBairro.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pnlGeral.add(txtDescrBairro);
        txtDescrBairro.setBounds(264, 63, 402, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Descrição");
        pnlGeral.add(jLabel5);
        jLabel5.setBounds(107, 92, 55, 14);

        txtDescicao.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pnlGeral.add(txtDescicao);
        txtDescicao.setBounds(166, 89, 500, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Complemento");
        pnlGeral.add(jLabel6);
        jLabel6.setBounds(83, 118, 79, 14);

        txtComplemento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pnlGeral.add(txtComplemento);
        txtComplemento.setBounds(166, 115, 373, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("CEP");
        pnlGeral.add(jLabel8);
        jLabel8.setBounds(557, 118, 20, 14);

        try {
            txtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCEP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCEPFocusGained(evt);
            }
        });
        pnlGeral.add(txtCEP);
        txtCEP.setBounds(581, 115, 85, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Ativo");
        pnlGeral.add(jLabel7);
        jLabel7.setBounds(132, 141, 30, 14);

        chkAtivo.setToolTipText("");
        pnlGeral.add(chkAtivo);
        chkAtivo.setBounds(166, 138, 21, 21);

        tablManutencao.addTab("Geral", pnlGeral);

        getContentPane().add(tablManutencao);
        tablManutencao.setBounds(0, 0, 713, 195);
        tablManutencao.getAccessibleContext().setAccessibleName("");

        pnlBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        pnlBotoes.setName("pnlBotao"); // NOI18N
        pnlBotoes.setPreferredSize(new java.awt.Dimension(229, 33));

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/confirmar.png"))); // NOI18N
        btnConfirmar.setText("Ok");
        btnConfirmar.setToolTipText("");
        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnConfirmar.setMaximumSize(new java.awt.Dimension(70, 20));
        btnConfirmar.setMinimumSize(new java.awt.Dimension(70, 20));
        btnConfirmar.setName("btnConfirmar"); // NOI18N
        btnConfirmar.setPreferredSize(new java.awt.Dimension(85, 25));
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnAjudar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ajudar.png"))); // NOI18N
        btnAjudar.setToolTipText("");
        btnAjudar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjudar.setMargin(new java.awt.Insets(5, 5, 5, 5));
        btnAjudar.setMaximumSize(new java.awt.Dimension(70, 20));
        btnAjudar.setMinimumSize(new java.awt.Dimension(70, 20));
        btnAjudar.setName("btnAjudar"); // NOI18N
        btnAjudar.setPreferredSize(new java.awt.Dimension(85, 25));
        btnAjudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjudarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnCancelar.setMaximumSize(new java.awt.Dimension(70, 20));
        btnCancelar.setMinimumSize(new java.awt.Dimension(70, 20));
        btnCancelar.setName("btnCancelar"); // NOI18N
        btnCancelar.setPreferredSize(new java.awt.Dimension(85, 25));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotoesLayout = new javax.swing.GroupLayout(pnlBotoes);
        pnlBotoes.setLayout(pnlBotoesLayout);
        pnlBotoesLayout.setHorizontalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAjudar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        pnlBotoesLayout.setVerticalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAjudar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBotoes);
        pnlBotoes.setBounds(0, 200, 713, 38);

        mnuArquivos.setText("Arquivo");
        mnuBarPrincipal.add(mnuArquivos);

        mnuAjuda.setText("Ajuda");
        mnuBarPrincipal.add(mnuAjuda);

        setJMenuBar(mnuBarPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        reescreverObjeto();

        Util.salvar(endereco, this, true);
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Util.cancelar(this);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAjudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjudarActionPerformed
        Util.ajudar("IFrmManEndereco");
    }//GEN-LAST:event_btnAjudarActionPerformed

    private void lblLocalizarTipoEnderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLocalizarTipoEnderMouseReleased
        boolean[] acoes = Util.getAcoesUsuario(Principal.TIPOS_ENDERECOS);
            
        if (!acoes[Util.CONSULTAR]) {
            JOptionPane.showMessageDialog(this.getParent(),
                    "Você não pode efetuar esta consultadas.\n\nMotivo: "
                            + "Usuário sem permissão.");
        } else {
            try {
                IFrmPesqTiposEnderecos iFrmPesqTiposEnderecos
                        = new IFrmPesqTiposEnderecos(new IFrmManTipoEndereco(
                                        new TiposEnderecos()), txtCodTipoEnder,
                                txtDescrTipoEnder);

                this.getParent().remove(iFrmPesqTiposEnderecos);
                this.getParent().add(iFrmPesqTiposEnderecos);

                Util.centralizar(this.getParent(), iFrmPesqTiposEnderecos);

                iFrmPesqTiposEnderecos.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this.getParent(),
                        "Tipo de endereço não pode ser consultado.\n\nMotivo: " + e);
            }
        }
    }//GEN-LAST:event_lblLocalizarTipoEnderMouseReleased

    private void lblLocalizarBairroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLocalizarBairroMouseReleased
        boolean[] acoes = Util.getAcoesUsuario(Principal.BAIRROS);
            
        if (!acoes[Util.CONSULTAR]) {
            JOptionPane.showMessageDialog(this.getParent(),
                    "Você não pode efetuar esta consultadas.\n\nMotivo: "
                            + "Usuário sem permissão.");
        } else {        
            try {
                IFrmPesqBairros iFrmPesqBairros
                        = new IFrmPesqBairros(new IFrmManBairro(new Bairros()),
                                txtCodBairro, txtDescrBairro);

                this.getParent().remove(iFrmPesqBairros);
                this.getParent().add(iFrmPesqBairros);

                Util.centralizar(this.getParent(), iFrmPesqBairros);

                iFrmPesqBairros.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this.getParent(),
                        "Bairro não pode ser consultado.\n\nMotivo: " + e);
            }
        }
    }//GEN-LAST:event_lblLocalizarBairroMouseReleased

    private void txtCodTipoEnderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodTipoEnderFocusLost
        pesquisarCodigoDescicaoTipoEndereco(new TiposEnderecos());
    }//GEN-LAST:event_txtCodTipoEnderFocusLost

    private void txtCodBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodBairroFocusLost
        pesquisarCodigoDescicaoBairro(new Bairros());
    }//GEN-LAST:event_txtCodBairroFocusLost

    private void txtCEPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCEPFocusGained
        txtCEP.selectAll();
    }//GEN-LAST:event_txtCEPFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjudar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JCheckBox chkAtivo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblLocalizarBairro;
    private javax.swing.JLabel lblLocalizarTipoEnder;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuArquivos;
    private javax.swing.JMenuBar mnuBarPrincipal;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JPanel pnlGeral;
    private javax.swing.JTabbedPane tablManutencao;
    private javax.swing.JFormattedTextField txtCEP;
    private javax.swing.JTextField txtCodBairro;
    private javax.swing.JTextField txtCodTipoEnder;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtDescicao;
    private javax.swing.JTextField txtDescrBairro;
    private javax.swing.JTextField txtDescrTipoEnder;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the endereco
     */
    public Enderecos getEndereco() {
        return endereco;
    }

    /**
     * @param endereco the endereco to set
     */
    public void setEndereco(Enderecos endereco) {
        this.endereco = endereco;
    }
}
