/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.samho.apresentacao;

import com.samho.negocio.PlanosSaude;
import com.samho.negocio.Principal;
import com.samho.negocio.TiposPlanosSaude;
import com.samho.util.Formatacao;
import com.samho.util.JTextFieldDocument;
import com.samho.util.Util;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 * Classe para visualização de objetos do tipo FrmManutencao.
 *
 * @author Saibel, Sergio Luis
 * @since  date 30/04/2017
 *
 * @version  revision 001.20170430 date 30/04/2017 author Saibel, Sérgio Luis reason
 * Conseguir instanciar um objeto do tipo FrmMaunutenção com os atributos e
 * métodos necessários. Esta classe tem como objetivo manipular os objetos 
 * definidos e ou obtidos a fim de manipular informações.
 * Esta extende um JInternalFrame ou seja necessita de um Frame como pai.
 * Métodos principais: Definição, Obtenção e Visualização do objeto.
 * Métodos secundários: Pesquisa de tipos de endereço e bairros
 * 
 */
public final class IFrmManTipoPlanoSaude extends JInternalFrame {

    // Declaração de atributos
    private TiposPlanosSaude tipoPlanoSaude;

    // Construtor
    public IFrmManTipoPlanoSaude(TiposPlanosSaude tipoPlanoSaude) throws Exception {
        initComponents();

        Util.limparCampos(rootPane);

        this.tipoPlanoSaude = tipoPlanoSaude;

        // Permite que somente números sejam informados neste campo
        txtCodigo.setDocument(new JTextFieldDocument(true));
        txtCodPlanoSaude.setDocument(new JTextFieldDocument(true));
        txtCarenciaMeses.setDocument(new JTextFieldDocument(true));
        // Converte para caixa alta a string informada no campo
        txtDescricao.setDocument(new JTextFieldDocument(false));

        carregarObjetoIFrmManutencao(tipoPlanoSaude);
    }

    public void carregarObjetoIFrmManutencao(TiposPlanosSaude tipoPlanoSaude) {
        try {
            if (tipoPlanoSaude.getIdTipoPlano()!= -1) {
                txtCodigo.setText(String.valueOf(
                        tipoPlanoSaude.getIdTipoPlano()));
            } else {
                txtCodigo.setText(String.valueOf(
                        tipoPlanoSaude.getTipoPlanoSaudeDAO().getProximoID()));
            }

            txtCodPlanoSaude.setText(String.valueOf(
                    tipoPlanoSaude.getCodPlanoSaude()));
            pesquisarCodigoDescicaoPlanoSaude(new PlanosSaude());
            txtDescricao.setText(tipoPlanoSaude.getDescricao());
            txtVlrDiferenca.setText(String.valueOf(
                    tipoPlanoSaude.getVlrDiferenca()));
            Formatacao.formatarDecimal2(txtVlrDiferenca);
            txtCarenciaMeses.setText(String.valueOf(
                    tipoPlanoSaude.getCarenciaMeses()));
            chkAtivo.setSelected(tipoPlanoSaude.isAtivo());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this.getParent(),
                    "Registro nao pode ser carregado.\n\nMotivo: " + ex);
        }
    }

    private void reescreverObjeto() {
        try {
            tipoPlanoSaude.setIdTipoPlano(Long.parseUnsignedLong(
                    txtCodigo.getText()));
            tipoPlanoSaude.setCodPlanoSaude(Long.parseUnsignedLong(
                    txtCodPlanoSaude.getText()));
            tipoPlanoSaude.setDescricao(txtDescricao.getText());
            tipoPlanoSaude.setVlrDiferenca(Double.valueOf(
                    Formatacao.ajustaDouble(txtVlrDiferenca.getText())));
            tipoPlanoSaude.setCarenciaMeses(Integer.parseUnsignedInt(
                    txtCarenciaMeses.getText()));
            tipoPlanoSaude.setAtivo(chkAtivo.isSelected());
            
            tipoPlanoSaude.adicionarCampos();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this.getParent(),
                    "Registro nao pode ser reescrito.\n\nMotivo: " + ex);
        }
    }

    public void pesquisarCodigoDescicaoPlanoSaude(PlanosSaude planoSaude) {
        Util.pesquisarCodigoDescicao(planoSaude, txtCodPlanoSaude,
                txtDescrPlanoSaude);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablManutencao = new javax.swing.JTabbedPane();
        pnlGeral = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodPlanoSaude = new javax.swing.JTextField();
        lblLocalizarPlanoSaude = new javax.swing.JLabel();
        txtDescrPlanoSaude = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtVlrDiferenca = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCarenciaMeses = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        chkAtivo = new javax.swing.JCheckBox();
        pnlBotoes = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        btnAjudar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        mnuBarPrincipal = new javax.swing.JMenuBar();
        mnuArquivos = new javax.swing.JMenu();
        mnuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Tipo de Plano Saúde");
        setMaximumSize(new java.awt.Dimension(730, 275));
        setMinimumSize(new java.awt.Dimension(730, 275));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(730, 275));
        setVerifyInputWhenFocusTarget(false);
        getContentPane().setLayout(null);

        tablManutencao.setMinimumSize(new java.awt.Dimension(713, 245));
        tablManutencao.setName(""); // NOI18N

        pnlGeral.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Cód. Tipo Plano");
        pnlGeral.add(jLabel2);
        jLabel2.setBounds(65, 24, 85, 14);

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(java.awt.SystemColor.info);
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pnlGeral.add(txtCodigo);
        txtCodigo.setBounds(154, 21, 70, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Cód. Plano Saúde");
        pnlGeral.add(jLabel3);
        jLabel3.setBounds(54, 50, 96, 14);

        txtCodPlanoSaude.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCodPlanoSaude.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodPlanoSaudeFocusLost(evt);
            }
        });
        pnlGeral.add(txtCodPlanoSaude);
        txtCodPlanoSaude.setBounds(154, 47, 70, 20);

        lblLocalizarPlanoSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/localizar.png"))); // NOI18N
        lblLocalizarPlanoSaude.setToolTipText("Localizar um tipo de endereço já cadastrado.");
        lblLocalizarPlanoSaude.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLocalizarPlanoSaude.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblLocalizarPlanoSaudeMouseReleased(evt);
            }
        });
        pnlGeral.add(lblLocalizarPlanoSaude);
        lblLocalizarPlanoSaude.setBounds(228, 47, 20, 20);

        txtDescrPlanoSaude.setEditable(false);
        txtDescrPlanoSaude.setBackground(java.awt.SystemColor.info);
        txtDescrPlanoSaude.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pnlGeral.add(txtDescrPlanoSaude);
        txtDescrPlanoSaude.setBounds(252, 47, 402, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Descrição");
        pnlGeral.add(jLabel5);
        jLabel5.setBounds(95, 76, 55, 14);

        txtDescricao.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pnlGeral.add(txtDescricao);
        txtDescricao.setBounds(154, 73, 500, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Valor Diferença");
        pnlGeral.add(jLabel6);
        jLabel6.setBounds(64, 102, 86, 14);

        txtVlrDiferenca.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVlrDiferenca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVlrDiferencaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVlrDiferencaFocusLost(evt);
            }
        });
        pnlGeral.add(txtVlrDiferenca);
        txtVlrDiferenca.setBounds(154, 99, 70, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Período Carência (meses)");
        pnlGeral.add(jLabel8);
        jLabel8.setBounds(262, 102, 150, 14);

        txtCarenciaMeses.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCarenciaMeses.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCarenciaMesesFocusGained(evt);
            }
        });
        pnlGeral.add(txtCarenciaMeses);
        txtCarenciaMeses.setBounds(410, 99, 70, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Ativo");
        pnlGeral.add(jLabel7);
        jLabel7.setBounds(120, 125, 30, 14);

        chkAtivo.setToolTipText("");
        pnlGeral.add(chkAtivo);
        chkAtivo.setBounds(154, 122, 21, 21);

        tablManutencao.addTab("Geral", pnlGeral);

        getContentPane().add(tablManutencao);
        tablManutencao.setBounds(0, 0, 710, 180);
        tablManutencao.getAccessibleContext().setAccessibleName("");

        pnlBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        pnlBotoes.setName("pnlBotao"); // NOI18N
        pnlBotoes.setPreferredSize(new java.awt.Dimension(229, 33));

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/confirmar.png"))); // NOI18N
        btnConfirmar.setText("Ok");
        btnConfirmar.setToolTipText("");
        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnConfirmar.setMaximumSize(new java.awt.Dimension(70, 20));
        btnConfirmar.setMinimumSize(new java.awt.Dimension(70, 20));
        btnConfirmar.setName("btnConfirmar"); // NOI18N
        btnConfirmar.setPreferredSize(new java.awt.Dimension(85, 25));
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnAjudar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ajudar.png"))); // NOI18N
        btnAjudar.setToolTipText("");
        btnAjudar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjudar.setMargin(new java.awt.Insets(5, 5, 5, 5));
        btnAjudar.setMaximumSize(new java.awt.Dimension(70, 20));
        btnAjudar.setMinimumSize(new java.awt.Dimension(70, 20));
        btnAjudar.setName("btnAjudar"); // NOI18N
        btnAjudar.setPreferredSize(new java.awt.Dimension(85, 25));
        btnAjudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjudarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnCancelar.setMaximumSize(new java.awt.Dimension(70, 20));
        btnCancelar.setMinimumSize(new java.awt.Dimension(70, 20));
        btnCancelar.setName("btnCancelar"); // NOI18N
        btnCancelar.setPreferredSize(new java.awt.Dimension(85, 25));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotoesLayout = new javax.swing.GroupLayout(pnlBotoes);
        pnlBotoes.setLayout(pnlBotoesLayout);
        pnlBotoesLayout.setHorizontalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAjudar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 493, Short.MAX_VALUE)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        pnlBotoesLayout.setVerticalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAjudar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBotoes);
        pnlBotoes.setBounds(0, 185, 713, 38);

        mnuArquivos.setText("Arquivo");
        mnuBarPrincipal.add(mnuArquivos);

        mnuAjuda.setText("Ajuda");
        mnuBarPrincipal.add(mnuAjuda);

        setJMenuBar(mnuBarPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        reescreverObjeto();

        Util.salvar(tipoPlanoSaude, this, true);
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Util.cancelar(this);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAjudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjudarActionPerformed
        Util.ajudar();
    }//GEN-LAST:event_btnAjudarActionPerformed

    private void lblLocalizarPlanoSaudeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLocalizarPlanoSaudeMouseReleased
         boolean[] acoes = Util.getAcoesUsuario(Principal.PLANOS_SAUDE);

        if (!acoes[Util.CONSULTAR]) {
            JOptionPane.showMessageDialog(this.getParent(),
                    "Você não pode efetuar esta consulta.\n\nMotivo: "
                            + "Usuário sem permissão.");
        } else {
            try {
                IFrmPesqPlanosSaude iFrmPesqPlanosSaude
                        = new IFrmPesqPlanosSaude(new IFrmManPlanoSaude(
                                new PlanosSaude()), txtCodPlanoSaude,
                                txtDescrPlanoSaude);

                this.getParent().remove(iFrmPesqPlanosSaude);
                this.getParent().add(iFrmPesqPlanosSaude);

                Util.centralizar(this.getParent(), iFrmPesqPlanosSaude);

                iFrmPesqPlanosSaude.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this.getParent(),
                        "Planos de Saúde não podem ser consultados.\n\nMotivo: " + e);
            }
        }
    }//GEN-LAST:event_lblLocalizarPlanoSaudeMouseReleased

    private void txtCodPlanoSaudeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodPlanoSaudeFocusLost
        pesquisarCodigoDescicaoPlanoSaude(new PlanosSaude());
    }//GEN-LAST:event_txtCodPlanoSaudeFocusLost

    private void txtVlrDiferencaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVlrDiferencaFocusGained
        txtVlrDiferenca.selectAll();
    }//GEN-LAST:event_txtVlrDiferencaFocusGained

    private void txtVlrDiferencaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVlrDiferencaFocusLost
        Formatacao.formatarDecimal2(txtVlrDiferenca);
    }//GEN-LAST:event_txtVlrDiferencaFocusLost

    private void txtCarenciaMesesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCarenciaMesesFocusGained
        txtCarenciaMeses.selectAll();
    }//GEN-LAST:event_txtCarenciaMesesFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjudar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JCheckBox chkAtivo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblLocalizarPlanoSaude;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuArquivos;
    private javax.swing.JMenuBar mnuBarPrincipal;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JPanel pnlGeral;
    private javax.swing.JTabbedPane tablManutencao;
    private javax.swing.JTextField txtCarenciaMeses;
    private javax.swing.JTextField txtCodPlanoSaude;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescrPlanoSaude;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtVlrDiferenca;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tipoPlanoSaude
     */
    public TiposPlanosSaude getTipoPlanoSaude() {
        return tipoPlanoSaude;
    }

    /**
     * @param tipoPlanoSaude the tipoPlanoSaude to set
     */
    public void setTipoPlanoSaude(TiposPlanosSaude tipoPlanoSaude) {
        this.tipoPlanoSaude = tipoPlanoSaude;
    }
}
