/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.samho.apresentacao;

import com.samho.dao.UsuariosDAO;
import com.samho.negocio.Acoes;
import com.samho.negocio.AcoesUsuarios;
import com.samho.negocio.Principal;
import com.samho.negocio.Usuarios;
import com.samho.util.JTextFieldDocument;
import com.samho.util.Util;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 * Classe para visualização de objetos do tipo FrmManutencao.
 *
 * @author Saibel, Sergio Luis
 * @since  date 06/04/2017
 *
 * @version  revision 001.20170406 date 06/04/2017 author Saibel, Sérgio Luis reason
 * Conseguir instanciar um objeto do tipo FrmMaunutenção com os atributos e
 * métodos necessários. Esta classe tem como objetivo manipular os objetos 
 * definidos e ou obtidos a fim de manipular informações.
 * Esta extende um JInternalFrame ou seja necessita de um Frame como pai.
 * Métodos principais: Definição, Obtenção e Visualização do objeto.
 * Métodos secundários: Pesquisa de tipos de endereço e bairros
 * 
 */
public final class IFrmManAcoesUsuario extends JInternalFrame {

    // Declaração de atributos
    private AcoesUsuarios acoesUsuario;

    // Construtor
    public IFrmManAcoesUsuario(AcoesUsuarios acoesUsuario) throws Exception {
        initComponents();

        Util.limparCampos(rootPane);

        this.acoesUsuario = acoesUsuario;

        // Permite que somente números sejam informados neste campo
        txtCodigo.setDocument(new JTextFieldDocument(true));
        txtCodAcao.setDocument(new JTextFieldDocument(true));
        txtCodUsuario.setDocument(new JTextFieldDocument(true));

        carregarObjetoIFrmManutencao(acoesUsuario);
    }

    public void carregarObjetoIFrmManutencao(AcoesUsuarios acoesUsuario) {
        try {
            if (acoesUsuario.getIdAcaoUsuario() != -1) {
                txtCodigo.setText(String.valueOf(acoesUsuario.getIdAcaoUsuario()));
            } else {
                txtCodigo.setText(String.valueOf(
                        acoesUsuario.getAcaoUsuarioDAO().getProximoID()));
            }

            txtCodAcao.setText(String.valueOf(acoesUsuario.getCodAcao()));
            pesquisarCodigoDescicaoAcao(new Acoes());
            
            txtCodUsuario.setText(String.valueOf(acoesUsuario.getCodUsuario()));
            pesquisarCodigoDescicaoUsuario(new Usuarios());

            chkIncluir.setSelected(acoesUsuario.isIncluir());
            chkAlterar.setSelected(acoesUsuario.isAlterar());
            chkExcluir.setSelected(acoesUsuario.isExcluir());
            chkConsultar.setSelected(acoesUsuario.isConsultar());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this.getParent(),
                    "Registro nao pode ser carregado.\n\nMotivo: " + ex);
        }
    }

    private void reescreverObjeto() {
        try {
            acoesUsuario.setIdAcaoUsuario(Long.parseUnsignedLong(
                    txtCodigo.getText()));
            acoesUsuario.setCodAcao(Long.parseUnsignedLong(
                    txtCodAcao.getText()));
            acoesUsuario.setCodUsuario(Long.parseUnsignedLong(
                    txtCodUsuario.getText()));
            acoesUsuario.setIncluir(chkIncluir.isSelected());
            acoesUsuario.setAlterar(chkAlterar.isSelected());
            acoesUsuario.setExcluir(chkExcluir.isSelected());
            acoesUsuario.setConsultar(chkConsultar.isSelected());

            acoesUsuario.adicionarCampos();
            
            // Atualiza as ações permitidas ao usuario
            UsuariosDAO.verificaAcoesUsuario();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this.getParent(),
                    "Registro nao pode ser reescrito.\n\nMotivo: " + ex);
        }
    }

    public void pesquisarCodigoDescicaoUsuario(Usuarios usuario) {
        Util.pesquisarCodigoDescicao(usuario, txtCodUsuario, txtDescrUsuario);
    }
    
    public void pesquisarCodigoDescicaoAcao(Acoes acao) {
        Util.pesquisarCodigoDescicao(acao, txtCodAcao, txtDescrAcao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablManutencao = new javax.swing.JTabbedPane();
        pnlGeral = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodAcao = new javax.swing.JTextField();
        lblLocalizarAcao = new javax.swing.JLabel();
        txtDescrAcao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodUsuario = new javax.swing.JTextField();
        lblLocalizarUsuario = new javax.swing.JLabel();
        txtDescrUsuario = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        chkIncluir = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        chkAlterar = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        chkExcluir = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        chkConsultar = new javax.swing.JCheckBox();
        pnlBotoes = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        btnAjudar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        mnuBarPrincipal = new javax.swing.JMenuBar();
        mnuArquivos = new javax.swing.JMenu();
        mnuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Ações do Usuário");
        setMaximumSize(new java.awt.Dimension(730, 281));
        setMinimumSize(new java.awt.Dimension(730, 281));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(730, 281));
        setVerifyInputWhenFocusTarget(false);
        getContentPane().setLayout(null);

        tablManutencao.setMinimumSize(new java.awt.Dimension(713, 245));
        tablManutencao.setName(""); // NOI18N

        pnlGeral.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Cód. Ação Usuário");
        pnlGeral.add(jLabel2);
        jLabel2.setBounds(46, 27, 101, 14);

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(java.awt.SystemColor.info);
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pnlGeral.add(txtCodigo);
        txtCodigo.setBounds(151, 24, 70, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Cód. Ação");
        pnlGeral.add(jLabel3);
        jLabel3.setBounds(92, 53, 55, 14);

        txtCodAcao.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCodAcao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodAcaoFocusLost(evt);
            }
        });
        pnlGeral.add(txtCodAcao);
        txtCodAcao.setBounds(151, 50, 70, 20);

        lblLocalizarAcao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/localizar.png"))); // NOI18N
        lblLocalizarAcao.setToolTipText("Localizar um tipo de endereço já cadastrado.");
        lblLocalizarAcao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLocalizarAcao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblLocalizarAcaoMouseReleased(evt);
            }
        });
        pnlGeral.add(lblLocalizarAcao);
        lblLocalizarAcao.setBounds(228, 50, 20, 20);

        txtDescrAcao.setEditable(false);
        txtDescrAcao.setBackground(java.awt.SystemColor.info);
        txtDescrAcao.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pnlGeral.add(txtDescrAcao);
        txtDescrAcao.setBounds(249, 50, 402, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Cód. Usuário");
        pnlGeral.add(jLabel4);
        jLabel4.setBounds(77, 79, 70, 14);

        txtCodUsuario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCodUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodUsuarioFocusLost(evt);
            }
        });
        pnlGeral.add(txtCodUsuario);
        txtCodUsuario.setBounds(151, 76, 70, 20);

        lblLocalizarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/localizar.png"))); // NOI18N
        lblLocalizarUsuario.setToolTipText("Localizar um tipo de endereço já cadastrado.");
        lblLocalizarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLocalizarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblLocalizarUsuarioMouseReleased(evt);
            }
        });
        pnlGeral.add(lblLocalizarUsuario);
        lblLocalizarUsuario.setBounds(228, 76, 20, 20);

        txtDescrUsuario.setEditable(false);
        txtDescrUsuario.setBackground(java.awt.SystemColor.info);
        txtDescrUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pnlGeral.add(txtDescrUsuario);
        txtDescrUsuario.setBounds(249, 76, 402, 20);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações do Usuário"));
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Incluir");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(55, 19, 36, 14);

        chkIncluir.setToolTipText("");
        jPanel1.add(chkIncluir);
        chkIncluir.setBounds(91, 16, 21, 21);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Alterar");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(182, 19, 40, 14);

        chkAlterar.setToolTipText("");
        jPanel1.add(chkAlterar);
        chkAlterar.setBounds(222, 16, 21, 21);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Excluir");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(311, 19, 37, 14);

        chkExcluir.setToolTipText("");
        jPanel1.add(chkExcluir);
        chkExcluir.setBounds(348, 16, 21, 21);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Consultar");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(426, 19, 54, 14);

        chkConsultar.setToolTipText("");
        jPanel1.add(chkConsultar);
        chkConsultar.setBounds(480, 16, 21, 21);

        pnlGeral.add(jPanel1);
        jPanel1.setBounds(110, 103, 540, 50);

        tablManutencao.addTab("Geral", pnlGeral);

        getContentPane().add(tablManutencao);
        tablManutencao.setBounds(0, 0, 713, 186);
        tablManutencao.getAccessibleContext().setAccessibleName("");

        pnlBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        pnlBotoes.setName("pnlBotao"); // NOI18N
        pnlBotoes.setPreferredSize(new java.awt.Dimension(229, 33));

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/confirmar.png"))); // NOI18N
        btnConfirmar.setText("Ok");
        btnConfirmar.setToolTipText("");
        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnConfirmar.setMaximumSize(new java.awt.Dimension(70, 20));
        btnConfirmar.setMinimumSize(new java.awt.Dimension(70, 20));
        btnConfirmar.setName("btnConfirmar"); // NOI18N
        btnConfirmar.setPreferredSize(new java.awt.Dimension(85, 25));
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnAjudar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ajudar.png"))); // NOI18N
        btnAjudar.setToolTipText("");
        btnAjudar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjudar.setMargin(new java.awt.Insets(5, 5, 5, 5));
        btnAjudar.setMaximumSize(new java.awt.Dimension(70, 20));
        btnAjudar.setMinimumSize(new java.awt.Dimension(70, 20));
        btnAjudar.setName("btnAjudar"); // NOI18N
        btnAjudar.setPreferredSize(new java.awt.Dimension(85, 25));
        btnAjudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjudarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnCancelar.setMaximumSize(new java.awt.Dimension(70, 20));
        btnCancelar.setMinimumSize(new java.awt.Dimension(70, 20));
        btnCancelar.setName("btnCancelar"); // NOI18N
        btnCancelar.setPreferredSize(new java.awt.Dimension(85, 25));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotoesLayout = new javax.swing.GroupLayout(pnlBotoes);
        pnlBotoes.setLayout(pnlBotoesLayout);
        pnlBotoesLayout.setHorizontalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAjudar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 493, Short.MAX_VALUE)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        pnlBotoesLayout.setVerticalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAjudar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBotoes);
        pnlBotoes.setBounds(0, 192, 713, 38);

        mnuArquivos.setText("Arquivo");
        mnuBarPrincipal.add(mnuArquivos);

        mnuAjuda.setText("Ajuda");
        mnuBarPrincipal.add(mnuAjuda);

        setJMenuBar(mnuBarPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        reescreverObjeto();

        Util.salvar(acoesUsuario, this, true);
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Util.cancelar(this);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAjudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjudarActionPerformed
        Util.ajudar("IFrmManAcoesUsuario");
    }//GEN-LAST:event_btnAjudarActionPerformed

    private void lblLocalizarAcaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLocalizarAcaoMouseReleased
        boolean[] acoes = Util.getAcoesUsuario(Principal.ACOES);
            
        if (!acoes[Util.CONSULTAR]) {
            JOptionPane.showMessageDialog(this.getParent(),
                    "Você não pode efetuar esta consultadas.\n\nMotivo: "
                            + "Usuário sem permissão.");
        } else {
            try {
                IFrmPesqAcoes iFrmPesqAcoes = new IFrmPesqAcoes(
                        new IFrmManAcao (new Acoes()), txtCodAcao, txtDescrAcao);

                this.getParent().remove(iFrmPesqAcoes);
                this.getParent().add(iFrmPesqAcoes);

                Util.centralizar(this.getParent(), iFrmPesqAcoes);

                iFrmPesqAcoes.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this.getParent(),
                        "Ações não podem ser consultadas.\n\nMotivo: " + e);
            }
        }
    }//GEN-LAST:event_lblLocalizarAcaoMouseReleased

    private void txtCodAcaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodAcaoFocusLost
        pesquisarCodigoDescicaoAcao(new Acoes());
    }//GEN-LAST:event_txtCodAcaoFocusLost

    private void txtCodUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodUsuarioFocusLost
        pesquisarCodigoDescicaoUsuario(new Usuarios());
    }//GEN-LAST:event_txtCodUsuarioFocusLost

    private void lblLocalizarUsuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLocalizarUsuarioMouseReleased
        boolean[] acoes = Util.getAcoesUsuario(Principal.USUARIOS);
            
        if (!acoes[Util.CONSULTAR]) {
            JOptionPane.showMessageDialog(this.getParent(),
                    "Você não pode efetuar esta consultadas.\n\nMotivo: "
                            + "Usuário sem permissão.");
        } else {
            try {
                IFrmPesqUsuarios iFrmPesqUsuarios = new IFrmPesqUsuarios(
                        new IFrmManUsuario (new Usuarios()), txtCodUsuario, 
                        txtDescrUsuario);

                this.getParent().remove(iFrmPesqUsuarios);
                this.getParent().add(iFrmPesqUsuarios);

                Util.centralizar(this.getParent(), iFrmPesqUsuarios);

                iFrmPesqUsuarios.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this.getParent(),
                        "Usuário não pode ser consultado.\n\nMotivo: " + e);
            }
        }
    }//GEN-LAST:event_lblLocalizarUsuarioMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjudar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JCheckBox chkAlterar;
    private javax.swing.JCheckBox chkConsultar;
    private javax.swing.JCheckBox chkExcluir;
    private javax.swing.JCheckBox chkIncluir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLocalizarAcao;
    private javax.swing.JLabel lblLocalizarUsuario;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuArquivos;
    private javax.swing.JMenuBar mnuBarPrincipal;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JPanel pnlGeral;
    private javax.swing.JTabbedPane tablManutencao;
    private javax.swing.JTextField txtCodAcao;
    private javax.swing.JTextField txtCodUsuario;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescrAcao;
    private javax.swing.JTextField txtDescrUsuario;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the acoesUsuario
     */
    public AcoesUsuarios getAcoesUsuario() {
        return acoesUsuario;
    }

    /**
     * @param acoesUsuario the acoesUsuario to set
     */
    public void setAcoesUsuario(AcoesUsuarios acoesUsuario) {
        this.acoesUsuario = acoesUsuario;
    }
}
